/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageRouteRouteImport } from './routes/manage/route'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as ManageMatchesRouteRouteImport } from './routes/manage/matches/route'
import { Route as ManagePlayersRouteRouteImport } from './routes/manage/players/route'
import { Route as ManageRolesRouteImport } from './routes/manage/roles'
import { Route as ManageSquadsRouteRouteImport } from './routes/manage/squads/route'
import { Route as ManageUsersRouteRouteImport } from './routes/manage/users/route'
import { Route as ManageMatchesIndexRouteImport } from './routes/manage/matches/index'
import { Route as ManageMatchesMatchIdRouteImport } from './routes/manage/matches/$matchId'
import { Route as ManageMatchesNewRouteImport } from './routes/manage/matches/new'
import { Route as ManagePlayersIndexRouteImport } from './routes/manage/players/index'
import { Route as ManagePlayersPlayerIdRouteImport } from './routes/manage/players/$playerId'
import { Route as ManagePlayersNewRouteImport } from './routes/manage/players/new'
import { Route as ManageSquadsIndexRouteImport } from './routes/manage/squads/index'
import { Route as ManageSquadsClubRouteRouteImport } from './routes/manage/squads/club/route'
import { Route as ManageSquadsNationalRouteRouteImport } from './routes/manage/squads/national/route'
import { Route as ManageUsersIndexRouteImport } from './routes/manage/users/index'
import { Route as ManageUsersUserIdRouteImport } from './routes/manage/users/$userId'
import { Route as ManageUsersNewRouteImport } from './routes/manage/users/new'
import { Route as ManageSquadsClubKeyRouteImport } from './routes/manage/squads/club/$key'
import { Route as ManageSquadsClubNewRouteImport } from './routes/manage/squads/club/new'
import { Route as ManageSquadsNationalKeyRouteImport } from './routes/manage/squads/national/$key'
import { Route as ManageSquadsNationalNewRouteImport } from './routes/manage/squads/national/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRouteRoute = ManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageMatchesRouteRoute = ManageMatchesRouteRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManagePlayersRouteRoute = ManagePlayersRouteRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageRolesRoute = ManageRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageSquadsRouteRoute = ManageSquadsRouteRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageUsersRouteRoute = ManageUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageMatchesIndexRoute = ManageMatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageMatchesRouteRoute,
} as any)
const ManageMatchesMatchIdRoute = ManageMatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => ManageMatchesRouteRoute,
} as any)
const ManageMatchesNewRoute = ManageMatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ManageMatchesRouteRoute,
} as any)
const ManagePlayersIndexRoute = ManagePlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagePlayersRouteRoute,
} as any)
const ManagePlayersPlayerIdRoute = ManagePlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => ManagePlayersRouteRoute,
} as any)
const ManagePlayersNewRoute = ManagePlayersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ManagePlayersRouteRoute,
} as any)
const ManageSquadsIndexRoute = ManageSquadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageSquadsRouteRoute,
} as any)
const ManageSquadsClubRouteRoute = ManageSquadsClubRouteRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => ManageSquadsRouteRoute,
} as any)
const ManageSquadsNationalRouteRoute =
  ManageSquadsNationalRouteRouteImport.update({
    id: '/national',
    path: '/national',
    getParentRoute: () => ManageSquadsRouteRoute,
  } as any)
const ManageUsersIndexRoute = ManageUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageUsersRouteRoute,
} as any)
const ManageUsersUserIdRoute = ManageUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ManageUsersRouteRoute,
} as any)
const ManageUsersNewRoute = ManageUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ManageUsersRouteRoute,
} as any)
const ManageSquadsClubKeyRoute = ManageSquadsClubKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ManageSquadsClubRouteRoute,
} as any)
const ManageSquadsClubNewRoute = ManageSquadsClubNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ManageSquadsClubRouteRoute,
} as any)
const ManageSquadsNationalKeyRoute = ManageSquadsNationalKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ManageSquadsNationalRouteRoute,
} as any)
const ManageSquadsNationalNewRoute = ManageSquadsNationalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ManageSquadsNationalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/manage/matches': typeof ManageMatchesRouteRouteWithChildren
  '/manage/players': typeof ManagePlayersRouteRouteWithChildren
  '/manage/squads': typeof ManageSquadsRouteRouteWithChildren
  '/manage/users': typeof ManageUsersRouteRouteWithChildren
  '/manage/roles': typeof ManageRolesRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/squads/club': typeof ManageSquadsClubRouteRouteWithChildren
  '/manage/squads/national': typeof ManageSquadsNationalRouteRouteWithChildren
  '/manage/matches/$matchId': typeof ManageMatchesMatchIdRoute
  '/manage/matches/new': typeof ManageMatchesNewRoute
  '/manage/players/$playerId': typeof ManagePlayersPlayerIdRoute
  '/manage/players/new': typeof ManagePlayersNewRoute
  '/manage/users/$userId': typeof ManageUsersUserIdRoute
  '/manage/users/new': typeof ManageUsersNewRoute
  '/manage/matches/': typeof ManageMatchesIndexRoute
  '/manage/players/': typeof ManagePlayersIndexRoute
  '/manage/squads/': typeof ManageSquadsIndexRoute
  '/manage/users/': typeof ManageUsersIndexRoute
  '/manage/squads/club/$key': typeof ManageSquadsClubKeyRoute
  '/manage/squads/club/new': typeof ManageSquadsClubNewRoute
  '/manage/squads/national/$key': typeof ManageSquadsNationalKeyRoute
  '/manage/squads/national/new': typeof ManageSquadsNationalNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage/roles': typeof ManageRolesRoute
  '/manage': typeof ManageIndexRoute
  '/manage/squads/club': typeof ManageSquadsClubRouteRouteWithChildren
  '/manage/squads/national': typeof ManageSquadsNationalRouteRouteWithChildren
  '/manage/matches/$matchId': typeof ManageMatchesMatchIdRoute
  '/manage/matches/new': typeof ManageMatchesNewRoute
  '/manage/players/$playerId': typeof ManagePlayersPlayerIdRoute
  '/manage/players/new': typeof ManagePlayersNewRoute
  '/manage/users/$userId': typeof ManageUsersUserIdRoute
  '/manage/users/new': typeof ManageUsersNewRoute
  '/manage/matches': typeof ManageMatchesIndexRoute
  '/manage/players': typeof ManagePlayersIndexRoute
  '/manage/squads': typeof ManageSquadsIndexRoute
  '/manage/users': typeof ManageUsersIndexRoute
  '/manage/squads/club/$key': typeof ManageSquadsClubKeyRoute
  '/manage/squads/club/new': typeof ManageSquadsClubNewRoute
  '/manage/squads/national/$key': typeof ManageSquadsNationalKeyRoute
  '/manage/squads/national/new': typeof ManageSquadsNationalNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/manage/matches': typeof ManageMatchesRouteRouteWithChildren
  '/manage/players': typeof ManagePlayersRouteRouteWithChildren
  '/manage/squads': typeof ManageSquadsRouteRouteWithChildren
  '/manage/users': typeof ManageUsersRouteRouteWithChildren
  '/manage/roles': typeof ManageRolesRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/squads/club': typeof ManageSquadsClubRouteRouteWithChildren
  '/manage/squads/national': typeof ManageSquadsNationalRouteRouteWithChildren
  '/manage/matches/$matchId': typeof ManageMatchesMatchIdRoute
  '/manage/matches/new': typeof ManageMatchesNewRoute
  '/manage/players/$playerId': typeof ManagePlayersPlayerIdRoute
  '/manage/players/new': typeof ManagePlayersNewRoute
  '/manage/users/$userId': typeof ManageUsersUserIdRoute
  '/manage/users/new': typeof ManageUsersNewRoute
  '/manage/matches/': typeof ManageMatchesIndexRoute
  '/manage/players/': typeof ManagePlayersIndexRoute
  '/manage/squads/': typeof ManageSquadsIndexRoute
  '/manage/users/': typeof ManageUsersIndexRoute
  '/manage/squads/club/$key': typeof ManageSquadsClubKeyRoute
  '/manage/squads/club/new': typeof ManageSquadsClubNewRoute
  '/manage/squads/national/$key': typeof ManageSquadsNationalKeyRoute
  '/manage/squads/national/new': typeof ManageSquadsNationalNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/manage/matches'
    | '/manage/players'
    | '/manage/squads'
    | '/manage/users'
    | '/manage/roles'
    | '/manage/'
    | '/manage/squads/club'
    | '/manage/squads/national'
    | '/manage/matches/$matchId'
    | '/manage/matches/new'
    | '/manage/players/$playerId'
    | '/manage/players/new'
    | '/manage/users/$userId'
    | '/manage/users/new'
    | '/manage/matches/'
    | '/manage/players/'
    | '/manage/squads/'
    | '/manage/users/'
    | '/manage/squads/club/$key'
    | '/manage/squads/club/new'
    | '/manage/squads/national/$key'
    | '/manage/squads/national/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage/roles'
    | '/manage'
    | '/manage/squads/club'
    | '/manage/squads/national'
    | '/manage/matches/$matchId'
    | '/manage/matches/new'
    | '/manage/players/$playerId'
    | '/manage/players/new'
    | '/manage/users/$userId'
    | '/manage/users/new'
    | '/manage/matches'
    | '/manage/players'
    | '/manage/squads'
    | '/manage/users'
    | '/manage/squads/club/$key'
    | '/manage/squads/club/new'
    | '/manage/squads/national/$key'
    | '/manage/squads/national/new'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/manage/matches'
    | '/manage/players'
    | '/manage/squads'
    | '/manage/users'
    | '/manage/roles'
    | '/manage/'
    | '/manage/squads/club'
    | '/manage/squads/national'
    | '/manage/matches/$matchId'
    | '/manage/matches/new'
    | '/manage/players/$playerId'
    | '/manage/players/new'
    | '/manage/users/$userId'
    | '/manage/users/new'
    | '/manage/matches/'
    | '/manage/players/'
    | '/manage/squads/'
    | '/manage/users/'
    | '/manage/squads/club/$key'
    | '/manage/squads/club/new'
    | '/manage/squads/national/$key'
    | '/manage/squads/national/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRouteRoute: typeof ManageRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/matches': {
      id: '/manage/matches'
      path: '/matches'
      fullPath: '/manage/matches'
      preLoaderRoute: typeof ManageMatchesRouteRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/players': {
      id: '/manage/players'
      path: '/players'
      fullPath: '/manage/players'
      preLoaderRoute: typeof ManagePlayersRouteRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/roles': {
      id: '/manage/roles'
      path: '/roles'
      fullPath: '/manage/roles'
      preLoaderRoute: typeof ManageRolesRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/squads': {
      id: '/manage/squads'
      path: '/squads'
      fullPath: '/manage/squads'
      preLoaderRoute: typeof ManageSquadsRouteRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/users': {
      id: '/manage/users'
      path: '/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof ManageUsersRouteRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/matches/': {
      id: '/manage/matches/'
      path: '/'
      fullPath: '/manage/matches/'
      preLoaderRoute: typeof ManageMatchesIndexRouteImport
      parentRoute: typeof ManageMatchesRouteRoute
    }
    '/manage/matches/$matchId': {
      id: '/manage/matches/$matchId'
      path: '/$matchId'
      fullPath: '/manage/matches/$matchId'
      preLoaderRoute: typeof ManageMatchesMatchIdRouteImport
      parentRoute: typeof ManageMatchesRouteRoute
    }
    '/manage/matches/new': {
      id: '/manage/matches/new'
      path: '/new'
      fullPath: '/manage/matches/new'
      preLoaderRoute: typeof ManageMatchesNewRouteImport
      parentRoute: typeof ManageMatchesRouteRoute
    }
    '/manage/players/': {
      id: '/manage/players/'
      path: '/'
      fullPath: '/manage/players/'
      preLoaderRoute: typeof ManagePlayersIndexRouteImport
      parentRoute: typeof ManagePlayersRouteRoute
    }
    '/manage/players/$playerId': {
      id: '/manage/players/$playerId'
      path: '/$playerId'
      fullPath: '/manage/players/$playerId'
      preLoaderRoute: typeof ManagePlayersPlayerIdRouteImport
      parentRoute: typeof ManagePlayersRouteRoute
    }
    '/manage/players/new': {
      id: '/manage/players/new'
      path: '/new'
      fullPath: '/manage/players/new'
      preLoaderRoute: typeof ManagePlayersNewRouteImport
      parentRoute: typeof ManagePlayersRouteRoute
    }
    '/manage/squads/': {
      id: '/manage/squads/'
      path: '/'
      fullPath: '/manage/squads/'
      preLoaderRoute: typeof ManageSquadsIndexRouteImport
      parentRoute: typeof ManageSquadsRouteRoute
    }
    '/manage/squads/club': {
      id: '/manage/squads/club'
      path: '/club'
      fullPath: '/manage/squads/club'
      preLoaderRoute: typeof ManageSquadsClubRouteRouteImport
      parentRoute: typeof ManageSquadsRouteRoute
    }
    '/manage/squads/national': {
      id: '/manage/squads/national'
      path: '/national'
      fullPath: '/manage/squads/national'
      preLoaderRoute: typeof ManageSquadsNationalRouteRouteImport
      parentRoute: typeof ManageSquadsRouteRoute
    }
    '/manage/users/': {
      id: '/manage/users/'
      path: '/'
      fullPath: '/manage/users/'
      preLoaderRoute: typeof ManageUsersIndexRouteImport
      parentRoute: typeof ManageUsersRouteRoute
    }
    '/manage/users/$userId': {
      id: '/manage/users/$userId'
      path: '/$userId'
      fullPath: '/manage/users/$userId'
      preLoaderRoute: typeof ManageUsersUserIdRouteImport
      parentRoute: typeof ManageUsersRouteRoute
    }
    '/manage/users/new': {
      id: '/manage/users/new'
      path: '/new'
      fullPath: '/manage/users/new'
      preLoaderRoute: typeof ManageUsersNewRouteImport
      parentRoute: typeof ManageUsersRouteRoute
    }
    '/manage/squads/club/$key': {
      id: '/manage/squads/club/$key'
      path: '/$key'
      fullPath: '/manage/squads/club/$key'
      preLoaderRoute: typeof ManageSquadsClubKeyRouteImport
      parentRoute: typeof ManageSquadsClubRouteRoute
    }
    '/manage/squads/club/new': {
      id: '/manage/squads/club/new'
      path: '/new'
      fullPath: '/manage/squads/club/new'
      preLoaderRoute: typeof ManageSquadsClubNewRouteImport
      parentRoute: typeof ManageSquadsClubRouteRoute
    }
    '/manage/squads/national/$key': {
      id: '/manage/squads/national/$key'
      path: '/$key'
      fullPath: '/manage/squads/national/$key'
      preLoaderRoute: typeof ManageSquadsNationalKeyRouteImport
      parentRoute: typeof ManageSquadsNationalRouteRoute
    }
    '/manage/squads/national/new': {
      id: '/manage/squads/national/new'
      path: '/new'
      fullPath: '/manage/squads/national/new'
      preLoaderRoute: typeof ManageSquadsNationalNewRouteImport
      parentRoute: typeof ManageSquadsNationalRouteRoute
    }
  }
}

interface ManageMatchesRouteRouteChildren {
  ManageMatchesMatchIdRoute: typeof ManageMatchesMatchIdRoute
  ManageMatchesNewRoute: typeof ManageMatchesNewRoute
  ManageMatchesIndexRoute: typeof ManageMatchesIndexRoute
}

const ManageMatchesRouteRouteChildren: ManageMatchesRouteRouteChildren = {
  ManageMatchesMatchIdRoute: ManageMatchesMatchIdRoute,
  ManageMatchesNewRoute: ManageMatchesNewRoute,
  ManageMatchesIndexRoute: ManageMatchesIndexRoute,
}

const ManageMatchesRouteRouteWithChildren =
  ManageMatchesRouteRoute._addFileChildren(ManageMatchesRouteRouteChildren)

interface ManagePlayersRouteRouteChildren {
  ManagePlayersPlayerIdRoute: typeof ManagePlayersPlayerIdRoute
  ManagePlayersNewRoute: typeof ManagePlayersNewRoute
  ManagePlayersIndexRoute: typeof ManagePlayersIndexRoute
}

const ManagePlayersRouteRouteChildren: ManagePlayersRouteRouteChildren = {
  ManagePlayersPlayerIdRoute: ManagePlayersPlayerIdRoute,
  ManagePlayersNewRoute: ManagePlayersNewRoute,
  ManagePlayersIndexRoute: ManagePlayersIndexRoute,
}

const ManagePlayersRouteRouteWithChildren =
  ManagePlayersRouteRoute._addFileChildren(ManagePlayersRouteRouteChildren)

interface ManageSquadsClubRouteRouteChildren {
  ManageSquadsClubKeyRoute: typeof ManageSquadsClubKeyRoute
  ManageSquadsClubNewRoute: typeof ManageSquadsClubNewRoute
}

const ManageSquadsClubRouteRouteChildren: ManageSquadsClubRouteRouteChildren = {
  ManageSquadsClubKeyRoute: ManageSquadsClubKeyRoute,
  ManageSquadsClubNewRoute: ManageSquadsClubNewRoute,
}

const ManageSquadsClubRouteRouteWithChildren =
  ManageSquadsClubRouteRoute._addFileChildren(
    ManageSquadsClubRouteRouteChildren,
  )

interface ManageSquadsNationalRouteRouteChildren {
  ManageSquadsNationalKeyRoute: typeof ManageSquadsNationalKeyRoute
  ManageSquadsNationalNewRoute: typeof ManageSquadsNationalNewRoute
}

const ManageSquadsNationalRouteRouteChildren: ManageSquadsNationalRouteRouteChildren =
  {
    ManageSquadsNationalKeyRoute: ManageSquadsNationalKeyRoute,
    ManageSquadsNationalNewRoute: ManageSquadsNationalNewRoute,
  }

const ManageSquadsNationalRouteRouteWithChildren =
  ManageSquadsNationalRouteRoute._addFileChildren(
    ManageSquadsNationalRouteRouteChildren,
  )

interface ManageSquadsRouteRouteChildren {
  ManageSquadsClubRouteRoute: typeof ManageSquadsClubRouteRouteWithChildren
  ManageSquadsNationalRouteRoute: typeof ManageSquadsNationalRouteRouteWithChildren
  ManageSquadsIndexRoute: typeof ManageSquadsIndexRoute
}

const ManageSquadsRouteRouteChildren: ManageSquadsRouteRouteChildren = {
  ManageSquadsClubRouteRoute: ManageSquadsClubRouteRouteWithChildren,
  ManageSquadsNationalRouteRoute: ManageSquadsNationalRouteRouteWithChildren,
  ManageSquadsIndexRoute: ManageSquadsIndexRoute,
}

const ManageSquadsRouteRouteWithChildren =
  ManageSquadsRouteRoute._addFileChildren(ManageSquadsRouteRouteChildren)

interface ManageUsersRouteRouteChildren {
  ManageUsersUserIdRoute: typeof ManageUsersUserIdRoute
  ManageUsersNewRoute: typeof ManageUsersNewRoute
  ManageUsersIndexRoute: typeof ManageUsersIndexRoute
}

const ManageUsersRouteRouteChildren: ManageUsersRouteRouteChildren = {
  ManageUsersUserIdRoute: ManageUsersUserIdRoute,
  ManageUsersNewRoute: ManageUsersNewRoute,
  ManageUsersIndexRoute: ManageUsersIndexRoute,
}

const ManageUsersRouteRouteWithChildren =
  ManageUsersRouteRoute._addFileChildren(ManageUsersRouteRouteChildren)

interface ManageRouteRouteChildren {
  ManageMatchesRouteRoute: typeof ManageMatchesRouteRouteWithChildren
  ManagePlayersRouteRoute: typeof ManagePlayersRouteRouteWithChildren
  ManageSquadsRouteRoute: typeof ManageSquadsRouteRouteWithChildren
  ManageUsersRouteRoute: typeof ManageUsersRouteRouteWithChildren
  ManageRolesRoute: typeof ManageRolesRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteRouteChildren: ManageRouteRouteChildren = {
  ManageMatchesRouteRoute: ManageMatchesRouteRouteWithChildren,
  ManagePlayersRouteRoute: ManagePlayersRouteRouteWithChildren,
  ManageSquadsRouteRoute: ManageSquadsRouteRouteWithChildren,
  ManageUsersRouteRoute: ManageUsersRouteRouteWithChildren,
  ManageRolesRoute: ManageRolesRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteRouteWithChildren = ManageRouteRoute._addFileChildren(
  ManageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRouteRoute: ManageRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
