/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageRouteRouteImport } from './routes/manage/route'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as ManageRolesRouteImport } from './routes/manage/roles'
import { Route as ManageUsersRouteImport } from './routes/manage/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRouteRoute = ManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageRolesRoute = ManageRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/manage/roles': typeof ManageRolesRoute
  '/manage/users': typeof ManageUsersRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage/roles': typeof ManageRolesRoute
  '/manage/users': typeof ManageUsersRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/manage/roles': typeof ManageRolesRoute
  '/manage/users': typeof ManageUsersRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage' | '/manage/roles' | '/manage/users' | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage/roles' | '/manage/users' | '/manage'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/manage/roles'
    | '/manage/users'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRouteRoute: typeof ManageRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/roles': {
      id: '/manage/roles'
      path: '/roles'
      fullPath: '/manage/roles'
      preLoaderRoute: typeof ManageRolesRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/users': {
      id: '/manage/users'
      path: '/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof ManageRouteRoute
    }
  }
}

interface ManageRouteRouteChildren {
  ManageRolesRoute: typeof ManageRolesRoute
  ManageUsersRoute: typeof ManageUsersRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteRouteChildren: ManageRouteRouteChildren = {
  ManageRolesRoute: ManageRolesRoute,
  ManageUsersRoute: ManageUsersRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteRouteWithChildren = ManageRouteRoute._addFileChildren(
  ManageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRouteRoute: ManageRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
